export { default as ChevronDownSmallIcon } from './chevron-down-small'
export { default as ChevronUpSmallIcon } from './chevron-up-small'
export { default as GitHubIcon } from './github'
export { default as ShoppingCartIcon } from './shopping-cart'
export { default as TwitterIcon } from './twitter'
export { default as XSmallIcon } from './x-small'
